---
title: "Category analysis"
author: "Andrew Lampinen"
output: html_document
---

```{r}
library(tidyverse)
```

# data loading

```{r}
parent_dir = ".."
subdirs = c(#"results_0", #"results_1", 
            #"results_2",
            #"results_3", "results_4",
            #"results_5", "results_6",
            #"results_7", 
            #"results_8",# "results_9",
            #"results_10", 
            #"results_11", #"results_12",
            #"results_13", "results_14",
            #"results_15",
            #"results_16", "results_17", "results_18", "results_19",
            #"results_20", 
            #"results_21", "results_22",
            #"results_23", "results_24", "results_25", 
            #"results_26", "results_27",
            #"results_28", "results_29",
            #"results_30", 
            #"results_31", #"results_32",
            #"results_33", "results_34", "results_35", 
            #"results_36", "results_37", "results_38",
            #"results_40", "results_41", "results_42", "results_43",
            #"results_44",
            #"results_45", 
            #"results_46", "results_47", "results_48", 
            #"results_49",
            ## without negation
            #"results_50", "results_51", "results_52",
            #"results_53", "results_54",
            ## contrasting examples
            #"results_55", "results_56", "results_57", "results_58", "results_59", "results_60",
            #"results_61", "results_62", "results_63", "results_64",
            # weight norm
            #"results_65", "results_66",
            #"results_67", "results_68",
            #"results_69", "results_70",
            #"results_71",
            #"results_72", "results_73", #"results_74",
            #"results_75", "results_76", "results_77",
            # even more tasks
            #"results_78", "results_79", "results_80",
            # no size meta
            #"results_81",
            #"results_82", "results_83", "results_84", 
            #"results_85",
            #"results_86", #"results_87", "results_88", 
            #"results_89",
            #"results_90", "results_91", "results_92", "results_93"
            ## Crucial bugfix in stimulus generation
            #"results_94",
            #"results_95",# "results_96", "results_97", "results_98", "results_99"
            #"results_100", 
            #"results_101", #"results_102", "results_103", "results_104"
            #"results_105", "results_106", "results_107", "results_108
            #"results_109"#, "results_110"
            #"results_123"
            ## Bugfix in meta-mapping domains
            #"results_117", "results_118", "results_119", "results_120"
            "results_123", "results_124", "results_125"
            )

lang_subdirs = c("results_123/language")
lang_homm_subdirs = c("results_123/language_HoMM", "results_124/language_HoMM", "results_125/language_HoMM")
num_runs = 5
```

```{r}
read_config = function(config_file) { 
  config = read_delim(config_file, delim="\n") %>%
    separate(`key, value`, c("key", "value"), sep=",", extra="merge") %>%
    spread(key, value) %>%
    mutate_at(c("base_train_tasks", "base_eval_tasks", "meta_class_train_tasks", "meta_class_eval_tasks", "meta_map_train_tasks", "meta_map_eval_tasks"), function(x) {
      x = gsub("\\\"|[][]| |\'", "", x)
      return(str_split(x, ","))
    } )
}
```

```{r}
load_d = function(results_dir, result_subdirs, num_runs, file_type) {
  d = replicate(num_runs * length(result_subdirs), data.frame())
  index = 1
  for (run_i in 0:(num_runs-1)) {
    for (result_subdir in result_subdirs) {
      filename = sprintf("%s/%s/run%i_%s.csv", results_dir, result_subdir, run_i, file_type)
      print(filename)
      if (!file.exists(filename)) {
        print(paste("skipping ", filename, sep=""))
        next
      }
      if (grepl("config", file_type)) {
        this_d = read_config(filename)
      } else {
        this_d = read.csv(filename, check.names=F, header=T) 
        names(this_d) <- make.unique(names(this_d)) 

      }
      this_d = this_d %>%
        mutate(run = run_i,
               run_type = result_subdir)
      d[[index]] = this_d
      index = index + 1
    }
    
  }
  d = bind_rows(d)
  return(d)
}
```

```{r}
config_d = load_d(parent_dir, subdirs, num_runs, "run_config")
loss_d = load_d(parent_dir, subdirs, num_runs, "losses")
lang_loss_d = load_d(parent_dir, lang_subdirs, num_runs, "language_losses")
meta_true_d = load_d(parent_dir, subdirs, num_runs, "meta_true_losses")
lang_meta_true_d = load_d(parent_dir, lang_homm_subdirs, num_runs, "language_meta_true_losses")
```

# some manipulation

```{r}
loss_d = loss_d %>%
  filter(epoch %% 100 == 0) %>%
  gather(task_and_train_or_eval, loss, -epoch, -run, -run_type) %>%
  separate(task_and_train_or_eval, c("task", "train_or_eval"), sep=":") %>%
  mutate(meta = grepl("is_|switch_|^NOT$", task),
         accuracy = grepl("accuracy", task),
         meta_task_type = case_when(!meta ~ "NA",
                                    task == "NOT" ~ "NOT",
                                    grepl("switch_color", task) ~ "switch_color",
                                    grepl("switch_shape", task) ~ "switch_shape",
                                    grepl("switch_size", task) ~ "switch_size"),
         composite = ifelse(grepl("AND|OR|XOR", task), "composite", "basic"),
         color_relevant = grepl("color", task),
         shape_relevant = grepl("shape", task),
         size_relevant = grepl("size", task))
  
```

```{r}
lang_loss_d = lang_loss_d %>%
  filter(epoch %% 100 == 0) %>%
  gather(task_and_train_or_eval, loss, -epoch, -run, -run_type) %>%
  separate(task_and_train_or_eval, c("task", "train_or_eval"), sep=":") %>%
  mutate(accuracy = grepl("accuracy", task),
         composite = ifelse(grepl("AND|OR|XOR", task), "composite", "basic"),
         composite_type = str_extract(task, "AND|OR|XOR"),
         color_relevant = grepl("color", task),
         shape_relevant = grepl("shape", task),
         size_relevant = grepl("size", task))
```


```{r}
meta_true_d = meta_true_d %>%
  filter(epoch %% 100 == 0) %>%
  gather(task, loss, -epoch, -run, -run_type) %>%
  separate(task, c("meta_task", "mapping_toe", "base_task_toe", "source", "target"), ":|->") %>%
  mutate(meta_task_type = case_when(meta_task == "NOT" ~ "NOT",
                                    grepl("switch_color", meta_task) ~ "switch_color",
                                    grepl("switch_shape", meta_task) ~ "switch_shape",
                                    grepl("switch_size", meta_task) ~ "switch_size"),
         base_task_type = case_when(grepl("AND|OR|XOR", source) ~ "composite",
                                    T ~ "basic"),
         base_composite_type = str_extract(source, "AND|OR|XOR"))
  
```

```{r}
lang_meta_true_d = lang_meta_true_d %>%
  filter(epoch %% 100 == 0) %>%
  gather(task, loss, -epoch, -run, -run_type) %>%
  separate(task, c("meta_task", "mapping_toe", "base_task_toe", "source", "target"), ":|->") %>%
  mutate(meta_task_type = case_when(meta_task == "NOT" ~ "NOT",
                                    grepl("switch_color", meta_task) ~ "switch_color",
                                    grepl("switch_shape", meta_task) ~ "switch_shape",
                                    grepl("switch_size", meta_task) ~ "switch_size"),
         base_task_type = case_when(grepl("AND|OR|XOR", source) ~ "composite",
                                    T ~ "basic"),
         base_composite_type = str_extract(source, "AND|OR|XOR"))
  
```


# basic plots
```{r}
theme_set(theme_classic())
```

```{r}
ggplot(loss_d %>% 
         filter(!meta),
       aes(x=epoch, y=loss, color=train_or_eval)) +
  geom_line(stat="summary",
            fun.y="mean") +
  facet_grid(run_type ~ accuracy, scales="free") 
```

```{r}
ggplot(loss_d %>% 
         filter(!meta,
                accuracy,
                run_type == "results_123"),
       aes(x=epoch, y=loss, color=train_or_eval)) +
  geom_line(stat="summary",
            fun.y="mean") +
  facet_grid(shape_relevant + color_relevant + size_relevant ~ composite + accuracy, scales="free") 
```


```{r}
ggplot(loss_d %>%
         filter(meta),
       aes(x=epoch, y=loss, color=train_or_eval)) +
  geom_line(stat="summary",
            fun.y="mean") +
  facet_grid(run_type ~ meta_task_type, scales="free") 
```

```{r}
ggplot(meta_true_d %>%
         filter(run_type == "results_123"),
       aes(x=epoch, y=loss, color=base_task_toe, linetype=mapping_toe)) +
  geom_line(stat="summary",
            fun.y="mean") +
  facet_grid(run ~ base_task_type + run_type, scales="free")
```

```{r}
ggplot(meta_true_d %>%
         filter(!grepl("results_123", run_type)),
       aes(x=epoch, y=loss, color=base_task_toe, linetype=mapping_toe)) +
  geom_line(stat="summary",
            fun.y="mean") +
  facet_grid(run ~ base_task_type + run_type, scales="free")
```

```{r}
ggplot(lang_meta_true_d %>%
         filter(!grepl("results_123", run_type)),
       aes(x=epoch, y=loss, color=base_task_toe, linetype=mapping_toe)) +
  geom_line(stat="summary",
            fun.y="mean") +
  facet_grid(run ~ base_task_type + run_type, scales="free")
```

# language baseline

```{r}
ggplot(lang_loss_d %>%
         filter(accuracy,
                grepl("123", run_type)),
       
       aes(x=epoch, y=loss, color=train_or_eval)) +
  geom_line(stat="summary",
            fun.y="mean") +
  facet_grid(run_type + color_relevant + shape_relevant + size_relevant ~ composite + composite_type, scales="free") 
```

```{r}
ggplot(lang_loss_d %>%
         filter(accuracy,
                grepl("123", run_type)),
       aes(x=epoch, y=loss, color=train_or_eval)) +
  geom_line(stat="summary",
            fun.y="mean") +
  facet_wrap(~run)
```

```{r}
ggplot(lang_loss_d %>%
         filter(accuracy,
                grepl("123", run_type)),
       aes(x=epoch, y=loss, color=train_or_eval)) +
  geom_line(stat="summary",
            fun.y="mean") 
```


# head to head comparison on harder tasks

```{r}
ggplot(lang_loss_d %>%
         filter(accuracy,
                composite == "composite",
                composite_type %in% c("AND", "XOR"),
                grepl("123", run_type)),
       aes(x=epoch, y=loss, color=train_or_eval)) +
  geom_line(stat="summary",
            fun.y="mean")
``` 


```{r}
ggplot(meta_true_d %>%
         filter(base_composite_type %in% c("AND", "XOR"), 
                run_type == "results_123"),
       aes(x=epoch, y=loss, color=base_task_toe, linetype=mapping_toe)) +
  geom_line(stat="summary",
            fun.y="mean") +
  facet_wrap(~meta_task_type)
```
```{r}
ggplot(lang_meta_true_d %>%
         filter(base_composite_type %in% c("AND", "XOR"), 
                grepl("123", run_type)),
       aes(x=epoch, y=loss, color=base_task_toe, linetype=mapping_toe)) +
  geom_line(stat="summary",
            fun.y="mean") +
  facet_wrap(run_type ~ meta_task_type)
```

# comparison

Some tasks may not appear as result of meta-mapping
```{r}
target_tasks_by_run =  meta_true_d %>%
  filter(epoch == 0,
         base_task_toe == "example_is_eval",
         mapping_toe == "metamapping_is_train",
         base_composite_type %in% c("AND", "XOR"), 
         grepl("123", run_type),
         !is.na(loss)) %>%
  select(run, source, target) %>%
  select(-source) %>%
  rename(task=target) %>%
  distinct()
```


This is a slightly sketchy because I don't have validation and eval tasks, but since I'm doing it the same for both HoMM and language, it's a fair comparison. 

```{r}
comparison_d = bind_rows(lang_loss_d %>%
                           filter(accuracy,
                                  train_or_eval == "eval",
                                  composite == "composite",
                                  composite_type %in% c("AND", "XOR"),
                                  grepl("123", run_type),
                                  !is.na(loss)) %>%
                           mutate(task = gsub("_accuracy", "", task)) %>%
                           select(epoch, run, run_type, task, loss) %>%
                           inner_join(target_tasks_by_run) %>%
                           group_by(run_type, run, epoch) %>%
                           summarise(mean_accuracy = mean(loss, na.rm=T)) %>%
                           group_by(run_type, run) %>%
                           filter(mean_accuracy == max(mean_accuracy)) %>%
                           ungroup(),
                         meta_true_d %>%
                           filter(base_task_toe == "example_is_eval",
                                  mapping_toe == "metamapping_is_train",
                                  base_composite_type %in% c("AND", "XOR"), 
                                  grepl("123", run_type)) %>%
                           group_by(run_type, run, epoch, target) %>%   # multiple mappings may produce same target                          
                           summarise(accuracy = mean(loss, na.rm=T)) %>%
                           group_by(run_type, run, epoch) %>%                           
                           summarise(mean_accuracy = mean(accuracy, na.rm=T)) %>%
                           group_by(run_type, run) %>%
                           filter(mean_accuracy == max(mean_accuracy)) %>%
                           ungroup(),
                         lang_meta_true_d %>%
                           filter(base_task_toe == "example_is_eval",
                                  mapping_toe == "metamapping_is_train",
                                  base_composite_type %in% c("AND", "XOR"), 
                                  grepl("123", run_type)) %>%
                           group_by(run_type, run, epoch, target) %>%   # multiple mappings may produce same target                          
                           summarise(accuracy = mean(loss, na.rm=T)) %>%
                           group_by(run_type, run, epoch) %>%                           
                           summarise(mean_accuracy = mean(accuracy, na.rm=T)) %>%
                           group_by(run_type, run) %>%
                           filter(mean_accuracy == max(mean_accuracy)) %>%
                           ungroup()) %>%
  mutate(run_type = case_when(grepl("language_HoMM", run_type) ~ "Lang_HoMM",
                              grepl("language", run_type) ~ "Lang",
                              T ~ "HoMM"),
         run_type = factor(run_type,
                           levels=c("HoMM", "Lang", "Lang_HoMM"),
                           labels=c("HoMM", "Language", "HoMM with language")))
```

## some quick tests

```{r}
perm_mean_diff_test = function(x, y, alpha=0.05) {
  obs_t = t.test(x, y)$statistic
  combined_data = c(x, y)
  n_combined = length(combined_data)
  n_x = length(x)
  perm_iterate = function(x, y) {
    perm = sample(n_combined)
    x_samp = combined_data[perm[1:n_x]]
    y_samp = combined_data[perm[-(1:n_x)]]
    this_t = t.test(x_samp, y_samp)$statistic
    return(this_t)
  }
  perms = replicate(500, perm_iterate(x, y))
  quants = quantile(perms, probs=c(alpha/2, 1-alpha/2))
  return(obs_t < quants[1] | obs_t > quants[2])
}
```

```{r}
set.seed(0)  # reproducibility
perm_mean_diff_test(
  comparison_d %>%
    filter(run_type == "HoMM") %>%
    pull(mean_accuracy),
  comparison_d %>%
    filter(run_type == "Language") %>%
    pull(mean_accuracy)
)

perm_mean_diff_test(
  comparison_d %>%
    filter(run_type == "HoMM") %>%
    pull(mean_accuracy),
  comparison_d %>%
    filter(run_type == "HoMM with language") %>%
    pull(mean_accuracy)
)

perm_mean_diff_test(
  comparison_d %>%
    filter(run_type == "Language") %>%
    pull(mean_accuracy),
  comparison_d %>%
    filter(run_type == "HoMM with language") %>%
    pull(mean_accuracy)
)
```

```{r}
contrasts(comparison_d$run_type) = cbind(HoMM=c(1, 0, 0), Lang=c(0, 1, 0))
lm(mean_accuracy~ run_type,
   comparison_d) %>%
  summary()
```


## and a plot

```{r}
ggplot(data=comparison_d %>%
         filter(run_type != "HoMM with language"),
       aes(x=run_type, 
           color=run_type,
           y=mean_accuracy)) +
  geom_hline(yintercept=1, linetype=2, alpha=0.5) +
  geom_hline(yintercept=0.5, linetype=3, alpha=0.5) +
  geom_errorbar(stat="summary",
                fun.data="mean_cl_boot",
                width=0.25,
                size=1) +
  geom_point(stat="summary",
             fun.y="mean",
             size=4) +
  scale_color_manual(values=c("#e41a1c", "#477ec8", "#984ea3")) +
  labs(x="Model type", y="Accuracy") +
  annotate("text", x=0.6, y=0.52, alpha=0.5, label="Chance") +
  annotate("text", x=0.7, y=1.02, alpha=0.5, label="Optimal adaptation") +
  # annotate("path",x=c(1,1,2,2),y=c(1.1,1.2,1.2,1.1),alpha=0.5) +
  # annotate("text", x=1.5, y=1.28, alpha=0.5, label="p < 0.05 (both perm- and t-test)") +
  scale_y_continuous(breaks = c(0.5, 0.75, 1), labels = c("50%", "75%", "100%")) +
  guides(color=F)

ggsave("../../../assorted_talks/HoMM/figures/categories_adaptation_no_lh.png", width=6, height=4)
```



```{r}
ggplot(data=comparison_d,
       aes(x=run_type, 
           color=run_type,
           y=mean_accuracy)) +
  geom_hline(yintercept=1, linetype=2, alpha=0.5) +
  geom_hline(yintercept=0.5, linetype=3, alpha=0.5) +
  geom_errorbar(stat="summary",
                fun.data="mean_cl_boot",
                width=0.25,
                size=1) +
  geom_point(stat="summary",
             fun.y="mean",
             size=4) +
  scale_color_manual(values=c("#e41a1c", "#477ec8", "#984ea3")) +
  labs(x="Model type", y="Accuracy") +
  annotate("text", x=0.6, y=0.52, alpha=0.5, label="Chance") +
  annotate("text", x=0.85, y=1.02, alpha=0.5, label="Optimal adaptation") +
  # annotate("path",x=c(1,1,2,2),y=c(1.1,1.2,1.2,1.1),alpha=0.5) +
  # annotate("text", x=1.5, y=1.28, alpha=0.5, label="p < 0.05 (both perm- and t-test)") +
  scale_y_continuous(breaks = c(0.5, 0.75, 1), labels = c("50%", "75%", "100%")) +
  guides(color=F)

ggsave("../../../assorted_talks/HoMM/figures/categories_adaptation.png", width=6, height=4)
```

